name: Deploy React App to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t cypher7/todoapp:${{ github.sha }} .

      - name: Tag Docker image as latest
        run: docker tag cypher7/todoapp:${{ github.sha }} cypher7/todoapp:latest

      - name: Push Docker image to Docker Hub
        run: docker push cypher7/todoapp:${{ github.sha }}
        run: docker push cypher7/todoapp:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            # Pull the latest Docker image
            docker pull cypher7/todoapp:latest || true
            
            # Stop and remove any existing container named todoapp
            docker stop todoapp || true
            docker rm todoapp || true
            
            # Run the new Docker container
            docker run -d -p 80:80 --name todoapp cypher7/todoapp:latest
            
            # Optional: Clean up unused images to save space
            docker image prune -f
            
            # Optional: Confirm the application is running
            curl -f http://localhost || echo "App is not responding"

